---
# tasks file for ansible-role-timezone

- name: Read OS specific variables
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_facts.distribution | lower }}-{{ ansible_facts.distribution_major_version }}.yml'
        - '{{ ansible_facts.distribution | lower }}.yml'
        - '{{ ansible_facts.os_family | lower }}.yml'
        - default.yml
      paths:
        - 'vars'

- name: Set the system timezone
  community.general.timezone:
    hwclock: "{{ timezone_hwclock | default(omit) }}"
    name: "{{ timezone_zonename }}"
  notify: Restart cron daemon
