---
# handlers file for ansible-role-timezone

- name: Restart cron daemon
  ansible.builtin.service:
    name: "{{ timezone_cron_daemon }}"
    state: restarted
  when: timezone_restart_cron_daemon_allowed
